default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: mv_listr_development

test:
  <<: *default
  database: mv_listr_test

production:
  <<: *default
  database: mv_listr_production
  username: mv_listr
  password: <%= ENV["DATABASE_PASSWORD"] %>
